In [2]:
import numpy as np

x1=[1,-1,1,-1,1,1]
x2=[-1,1,-1,-1,1,-1]
x3=[1,1,-1,1,1,1]

r=[1,1,1,-1,-1,-1]
print(np.dot(x1,r))
print(np.dot(x2,r))
print(np.dot(x3,r))

0
0
-2


In [29]:
2
3
4
5

from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
# define a matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# calculate the mean of each column
M = mean(A.T, axis=1)
print(M)
# center columns by subtracting column means
C = A - M
print(C)
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)
# eigendecomposition of covariance matrix
values, vectors = eig(V)
print(vectors)
print(values)
# project data
P = vectors.T.dot(C.T)
print(P.T)

[[1 2]
 [3 4]
 [5 6]]
[3. 4.]
[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]
[[4. 4.]
 [4. 4.]]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


Q2[1.5pts]:Repeat Q1 using XGBoost and LightGBM algorithms.Experiment with at least 5 different parametersettings to see their effect on training and test errors.How do best parameters change as the #training instances change? 

In [5]:

import numpy as np
# define a matrix

vector= np.array([[0.29, 0.37, 1,2],[-0.2, 0.3, -2,1]])

x= np.array([3, 0.2, 0.5, 1.0])

mean= np.array([0.3, -0.7, 1.0, 0.5])
print(vector)
print(x)
print(mean)

# project data
P = vector.dot(x-mean)
print(P.T)

[[ 0.29  0.37  1.    2.  ]
 [-0.2   0.3  -2.    1.  ]]
[3.  0.2 0.5 1. ]
[ 0.3 -0.7  1.   0.5]
[1.616 1.23 ]


In [196]:
import xgboost as xgb
from sklearn.metrics import accuracy_score

for i in range(5):
    print('model:', i+1)
    if i==0: 
        xg1=xgb.XGBClassifier(max_depth=5,learning_rate=.5)
        xg2=xgb.XGBClassifier(max_depth=5,learning_rate=.5)
    if i==1: 
        xg1=xgb.XGBClassifier(min_child_weight=1,gamma=0,max_depth=7,eval_metric='auc',learning_rate=.5)
        xg2=xgb.XGBClassifier(min_child_weight=1,gamma=0,max_depth=7,eval_metric='auc',learning_rate=.5)
    if i==2: 
        xg1=xgb.XGBClassifier(max_depth=7,objective='binary:logistic',eval_metric='auc',learning_rate=.1)
        xg2=xgb.XGBClassifier(max_depth=7,objective='binary:logistic',eval_metric='auc',learning_rate=.1)
    if i==3: 
        xg1=xgb.XGBClassifier(min_child_weight=5,max_depth=7,objective='binary:logistic',eval_metric='mae',learning_rate=.05)
        xg2=xgb.XGBClassifier(min_child_weight=5,max_depth=7,objective='binary:logistic',eval_metric='mae',learning_rate=.05)
    if i==4: 
        xg1=xgb.XGBClassifier(max_depth=9,objective='binary:logistic',eta=1,eval_metric='rmse',learning_rate=.05)
        xg2=xgb.XGBClassifier(max_depth=9,objective='binary:logistic',eta=1,eval_metric='rmse',learning_rate=.05)
    xg1.fit(x25_train,y25_train)
#     if i==0:
#         ypred=xg1.predict(x25_train)
#         print("Accuracy11111:",accuracy_score(ypred,y25_train))
    print('X25 Test Error= ', round(1-xg1.score(x25_test,y25_test),3))
    print('X25 Train Error= ', round(1-xg1.score(x25_train,y25_train),3))
    xg2.fit(x100_train,y100_train) 
    print('X100 Test Error= ', round(1-xg2.score(x100_test,y100_test),3))
    print('X100 Train Error= ', round(1-xg2.score(x100_train,y100_train),3))
    print()

model: 1
X25 Test Error=  0.084
X25 Train Error=  0.0
X100 Test Error=  0.052
X100 Train Error=  0.0

model: 2
X25 Test Error=  0.084
X25 Train Error=  0.0
X100 Test Error=  0.061
X100 Train Error=  0.0

model: 3
X25 Test Error=  0.108
X25 Train Error=  0.0
X100 Test Error=  0.061
X100 Train Error=  0.0

model: 4
X25 Test Error=  0.133
X25 Train Error=  0.012
X100 Test Error=  0.055
X100 Train Error=  0.003

model: 5
X25 Test Error=  0.12
X25 Train Error=  0.0
X100 Test Error=  0.064
X100 Train Error=  0.0



In [6]:
import lightgbm as lgb 

for i in range(5):
    print('model:', i+1)
    if i==0: 
        lg1=lgb.LGBMClassifier(num_leaves=50, max_depth=7,learning_rate=1)
        lg2=lgb.LGBMClassifier(num_leaves=50, max_depth=7,learning_rate=1)
    if i==1: 
        lg1=lgb.LGBMClassifier(num_leaves=50, max_depth=7,learning_rate=.9)
        lg2=lgb.LGBMClassifier(num_leaves=50, max_depth=7,learning_rate=.9)
    if i==2: 
        lg1=lgb.LGBMClassifier(num_leaves=200, objective='binary',max_depth=7,learning_rate=.01,max_bin=20)
        lg2=lgb.LGBMClassifier(num_leaves=200, objective='binary',max_depth=7,learning_rate=.01,max_bin=20)
    if i==3: 
        lg1=lgb.LGBMClassifier(num_leaves=20, objective='binary',max_depth=7,learning_rate=.05,max_bin=20)
        lg2=lgb.LGBMClassifier(num_leaves=20, objective='binary',max_depth=7,learning_rate=.05,max_bin=20)
    if i==4: 
        lg1=lgb.LGBMClassifier(num_leaves=500, objective='binary',max_depth=7,learning_rate=.5,max_bin=250)
        lg2=lgb.LGBMClassifier(num_leaves=500, objective='binary',max_depth=7,learning_rate=.5,max_bin=250)

    lg1.fit(x25_train,y25_train) 
    print('X25 Test Error= ', round(1-lg1.score(x25_test,y25_test),3))
    print('X25 Train Error= ', round(1-lg1.score(x25_train,y25_train),3))
    lg2.fit(x100_train,y100_train) 
    print('X100 Test Error= ', round(1-lg2.score(x100_test,y100_test),3))
    print('X100 Train Error= ', round(1-lg2.score(x100_train,y100_train),3))
    print()

model: 1
X25 Test Error=  0.759
X25 Train Error=  0.737
X100 Test Error=  0.609
X100 Train Error=  0.549

model: 2
X25 Test Error=  0.145
X25 Train Error=  0.0
X100 Test Error=  0.639
X100 Train Error=  0.622

model: 3
X25 Test Error=  0.133
X25 Train Error=  0.024
X100 Test Error=  0.115
X100 Train Error=  0.01

model: 4
X25 Test Error=  0.096
X25 Train Error=  0.0
X100 Test Error=  0.058
X100 Train Error=  0.0

model: 5
X25 Test Error=  0.096
X25 Train Error=  0.0
X100 Test Error=  0.064
X100 Train Error=  0.0



Q3[1.5pts]:Nonparametric Classification: Use sklearn.treelibrary’s KneighborsClassifieralgorithm. For the KneighborsClassifierdetermine the value of the best kparameter (experiment with k=1, 3, 5,9) that results in the best test error for each of thetraining data sets you created. How does the best kvalue change as the number of instances change? 

In [194]:
from sklearn.neighbors import KNeighborsClassifier

for i in 1,3,5,9:
    knn1 = KNeighborsClassifier(n_neighbors=i)
    knn2 = KNeighborsClassifier(n_neighbors=i)
    knn1.fit(x25_train ,y25_train)
    knn2.fit(x100_train ,y100_train)
#     ypred = knn1.predict(x25_test)
#     print(accuracy_score(ypred,y25_test))
    print('K:', i)
    print('X25 Test Error= ', round(1-knn1.score(x25_test,y25_test),3))
    print('X25 Train Error= ', round(1-knn1.score(x25_train,y25_train),3))
    print('X100 Test Error= ', round(1-knn2.score(x100_test,y100_test),3))
    print('X100 Train Error= ', round(1-knn2.score(x100_train,y100_train),3))
    print()




K: 1
X25 Test Error=  0.072
X25 Train Error=  0.0
X100 Test Error=  0.03
X100 Train Error=  0.0

K: 3
X25 Test Error=  0.072
X25 Train Error=  0.036
X100 Test Error=  0.03
X100 Train Error=  0.015

K: 5
X25 Test Error=  0.096
X25 Train Error=  0.048
X100 Test Error=  0.03
X100 Train Error=  0.022

K: 9
X25 Test Error=  0.096
X25 Train Error=  0.054
X100 Test Error=  0.042
X100 Train Error=  0.033



Q4[3pts]:Decision Trees, regression for digit completion: Using only the datafor class 6 and class 9in X100for training,  use the first 48features as inputs and predict the next 16 features, i.e. create 16 decision tree regression models, using the sklearn library. Report the test error(use only the instances from classes 6 and 9)for each of the 16 regression models. Which pixels are easier to predict?(Clarification, each of your models will have the same set of features, namely features 1...48

In [209]:
from sklearn.tree import DecisionTreeRegressor

print(X100.shape)
X100_69 = pd.concat([X100.loc[X100[64] == 6],X100.loc[X100[64] == 9]]).sort_index()
print(X100_69.shape)
# X100_69
print()
print('Test Error:')
for i in range(16):
    
    xtra, xtes, ytra, ytes = train_test_split(X100_69.iloc[:,0:48], X100_69.iloc[:,48+i], test_size=0.33)
    reg=DecisionTreeRegressor()
    reg.fit(xtra,ytra)
    ypred=reg.predict(xtes)
    print('Feature ',48+i,':',round(1-accuracy_score(ypred,ytes),3))
    


(1000, 65)
(200, 65)

Test Error:
Feature  48 : 0.0
Feature  49 : 0.288
Feature  50 : 0.652
Feature  51 : 0.758
Feature  52 : 0.879
Feature  53 : 0.788
Feature  54 : 0.758
Feature  55 : 0.303
Feature  56 : 0.0
Feature  57 : 0.076
Feature  58 : 0.636
Feature  59 : 0.818
Feature  60 : 0.818
Feature  61 : 0.773
Feature  62 : 0.667
Feature  63 : 0.136
